{
    'name': 'Pharma Discount Approval',
    'category': 'Users',
    'version': '0.1',
    'summary': '',
    'author': 'Acespritech Solutions Pvt. Ltd.',
    'sequence': 1,
    'website': '',
    'description': """ """,
    # 'price': 0.0,
    'currency': 'EUR',
    'license': 'LGPL-3',
    'depends': ['base', 'sale_management', 'pharma_sales_rep', 'account'],
    'data': [
        'security/ir.model.access.csv',
        'views/res_users_view.xml',
        'views/discount_view.xml',
        'wizard/invoice_discount_views.xml',
        'views/account_move_views.xml',
    ],
    'images': ['images/main_screenshot.png'],
    'installable': True,
    'application': True,
    'auto_install': False,
}
